# Generated by Django 5.0.2 on 2024-02-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_notes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
