# Generated by Django 5.0.2 on 2024-02-23 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_remove_notes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 23, 23, 54, 23, 857764)),
        ),
    ]
