# Generated by Django 5.0.2 on 2024-03-19 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0004_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
