# Generated by Django 5.0.2 on 2024-03-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0006_remove_notes_date_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesApp.notes')),
            ],
        ),
    ]
