# Generated by Django 5.0.2 on 2024-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0007_remove_notes_note_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
